import type { Metadata } from 'next'
import  {Footer, Navbar} from '@/components'
import './globals.css'



export const metadata: Metadata = {
  title: 'Create Next Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative">
       
        {children}
       
        </body>
    </html>
  )
}
